"""empty message

Revision ID: 22843e95d1ca
Revises: 6bad6a639d87
Create Date: 2025-06-06 21:10:09.530759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22843e95d1ca'
down_revision = '6bad6a639d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
