"""empty message

Revision ID: 6bad6a639d87
Revises: 6cb123c1a824
Create Date: 2025-06-06 21:06:24.738435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bad6a639d87'
down_revision = '6cb123c1a824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('personaje_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('personaje_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
